
[changelog]
header = """
# 更改日志 \n
"""
body = """
{% if version -%}
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
    ## [Unreleased]
{% endif -%}
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | split(pat="\n") | first | upper_first | trim }}\
    {% endfor %}
{% endfor %}\n
"""
footer = """
{% for release in releases -%}
    {% if release.version -%}
        {% if release.previous.version -%}
            [{{ release.version | trim_start_matches(pat="v") }}]: \
                https://github.com/SuperArilo/ARILIB/compare/{{ release.previous.version }}..{{ release.version }}
        {% else -%}
            [{{ release.version | trim_start_matches(pat="v") }}]: \
                https://github.com/SuperArilo/ARILIB/tree/{{ release.version }}
        {% endif -%}
    {% else -%}
        [unreleased]: https://github.com/SuperArilo/ARILIB/compare/{{ release.previous.version }}..HEAD
    {% endif -%}
{% endfor %}
<!-- generated by git-cliff -->
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
commit_parsers = [
    { message = "^[增|添]加", group = "Added" },
    { message = "^支持", group = "Added" },
    { message = "^新增", group = "Added" },
    { message = "^删除", group = "Removed" },
    { message = "^移除", group = "Removed" },
    { message = "^修复", group = "Fixed" },
    { message = "^修正", group = "Fixed" },
    { message = "^测试", group = "Fixed" },
    { message = "^更改", group = "Changed" },
    { message = "^更新", group = "Changed" },
    { message = "^重构", group = "Changed" },
    { message = "^优化", group = "Changed" },
    { message = "^调整", group = "Changed" },
    { message = "^[aA]dd", group = "Added" },
    { message = "^[sS]upport", group = "Added" },
    { message = "^[rR]emove", group = "Removed" },
    { message = "^.*: add", group = "Added" },
    { message = "^.*: support", group = "Added" },
    { message = "^.*: remove", group = "Removed" },
    { message = "^.*: delete", group = "Removed" },
    { message = "^test", group = "Fixed" },
    { message = "^fix", group = "Fixed" },
    { message = "^.*: fix", group = "Fixed" },
    { message = "^.*", group = "Changed" },
]
filter_commits = false
topo_order = false
sort_commits = "newest"