name: arilib
version: '${project.version}'
main: com.tty.lib.Lib
api-version: '1.21'
authors:
  - Arilo007
folia-supported: true
loader: com.tty.lib.Loader
dependencies:
  server:
    Vault:
      required: true
      load: BEFORE
    PlaceholderAPI:
      required: false
      load: BEFORE
    WorldGuard:
      required: false
      load: BEFORE
    Residence:
      required: false
      load: BEFORE
    Dominion:
      required: false
      load: BEFORE