name: arilib
version: '${project.version}'
main: com.tty.lib.Lib
api-version: '1.21'
authors:
  - Arilo007
folia-supported: true
loader: com.tty.lib.Loader
dependencies:
  server:
    ari:
      load: AFTER
      required: false
      join-classpath: true
