name: Build-ARILIB

on:
  push:
    tags: ['v*']
  workflow_dispatch:

env:
  JAVA_VERSION: '21'
  MAVEN_VERSION: '3.9.5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: PULL SOURCE CODE
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SETTING JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: SETTING MAVEN
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: ${{ env.MAVEN_VERSION }}

      - name: CLONE API
        uses: actions/checkout@v4
        with:
          repository: SuperArilo/ARILIB-API
          path: arilib-api

      - name: INSTALL API
        run: |
          cd arilib-api
          mvn clean install -DskipTests
          cd ..

      - name: SET VERSION FROM TAG
        id: version
        run: |
          TAG=${GITHUB_REF_NAME#v}
          echo "VERSION=$TAG" >> $GITHUB_OUTPUT
          mvn versions:set -DnewVersion=$TAG -DgenerateBackupPoms=false

      - name: BUILD
        run: mvn clean package -DskipTests -DoutputDirectory=target

      - name: COLLECT PRODUCTS
        run: |
          mkdir -p build-artifacts
          VERSION=${{ steps.version.outputs.VERSION }}
          cp target/arilib-*.jar build-artifacts/arilib-${VERSION}.jar

      - name: UPLOAD
        uses: actions/upload-artifact@v4
        with:
          name: jar-files
          path: build-artifacts/
          retention-days: 1

  create-release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: CHECKOUT CODE
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: DOWNLOAD ARTIFACTS
        uses: actions/download-artifact@v4
        with:
          name: jar-files
          path: build-artifacts

      - name: GENERATE CHANGELOG
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --latest --strip header
        env:
          OUTPUT: CHANGES.md

      - name: READ CHANGELOG CONTENT
        id: read_changelog
        run: |
          echo "body<<EOF" >> $GITHUB_OUTPUT
          cat CHANGES.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: CREATE RELEASE
        uses: softprops/action-gh-release@v3
        with:
          files: build-artifacts/*.jar
          body: ${{ steps.read_changelog.outputs.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}