name: Build-ARILIB

on:
  push:
    tags: ['v*']
  workflow_dispatch:

env:
  JAVA_VERSION: '21'
  MAVEN_VERSION: '3.9.5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: PULL SOURCE CODE
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SETTING JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: SETTING MAVEN
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: ${{ env.MAVEN_VERSION }}

      - name: GET TAG NAME
        id: tag
        run: echo "TAG=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: SET VERSION FROM TAG
        run: mvn versions:set -DnewVersion=${{ steps.tag.outputs.TAG }} -DgenerateBackupPoms=false

      - name:
        uses: actions/checkout@v4
        with:
          repository: SuperArilo/ARILIB-API
          path: arilib-api

      - name: INSTALL API
        run: |
          cd arilib-api
          mvn clean install -DskipTests
          cd ..

      - name: BUILD
        run: mvn clean package -DskipTests

      - name: COLLECT PRODUCTS
        run: |
          mkdir -p build-artifacts
          cp target/arilib*.jar build-artifacts/arilib.jar

      - name: UPLOAD
        uses: actions/upload-artifact@v4
        with:
          name: jar-files
          path: build-artifacts/
          retention-days: 1

  create-release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: DOWNLOAD
        uses: actions/download-artifact@v4
        with:
          name: jar-files
          path: build-artifacts

      - name: CREATE RELEASE
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: build-artifacts/*.jar
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}